# Generated by Django 3.2.25 on 2026-03-23 15:42

from django.db import migrations


GYMS = [
    {'name': 'Arkády',  'color': '#E6F1FB'},
    {'name': 'Pankrác', 'color': '#EAF3DE'},
    {'name': 'Chodov',  'color': '#FAEEDA'},
]

EXERCISES = [
    {'name': 'Bench Press',          'equipment': 'bar'},
    {'name': 'Deadlift',             'equipment': 'bar'},
    {'name': 'Lat Pulldown',         'equipment': 'pulley'},
    {'name': 'Leg Press',            'equipment': 'accessory'},
    {'name': 'Shoulder Press',       'equipment': 'bar'},
    {'name': 'Chest / Pec Press',   'equipment': 'accessory'},
    {'name': 'Squat / Hack Squat',  'equipment': 'bar'},
    {'name': 'Incline Bench Press',  'equipment': 'bar'},
    {'name': 'Decline Press',        'equipment': 'bar'},
    {'name': 'Pec Fly',              'equipment': 'accessory'},
    {'name': 'Seated / Low Row',     'equipment': 'pulley'},
    {'name': 'Leg Extension',        'equipment': 'accessory'},
    {'name': 'Leg Curl',             'equipment': 'accessory'},
    {'name': 'Lateral Raise',        'equipment': 'dumbbell'},
    {'name': 'Calves',               'equipment': 'accessory'},
    {'name': 'Biceps Curl',          'equipment': 'dumbbell'},
    {'name': 'Biceps (machine)',     'equipment': 'accessory'},
    {'name': 'Triceps',              'equipment': 'pulley'},
    {'name': 'Hip Abduction',        'equipment': 'accessory'},
    {'name': 'Hip Adduction',        'equipment': 'accessory'},
]


def seed_data(apps, schema_editor):
    Gym = apps.get_model('tracker', 'Gym')
    Exercise = apps.get_model('tracker', 'Exercise')

    for g in GYMS:
        Gym.objects.get_or_create(name=g['name'], defaults={'color': g['color']})

    for e in EXERCISES:
        Exercise.objects.get_or_create(name=e['name'], defaults={'equipment': e['equipment']})


def unseed_data(apps, schema_editor):
    Gym = apps.get_model('tracker', 'Gym')
    Exercise = apps.get_model('tracker', 'Exercise')

    Gym.objects.filter(name__in=[g['name'] for g in GYMS]).delete()
    Exercise.objects.filter(name__in=[e['name'] for e in EXERCISES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
